version: '3.8'

services:
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  keydb:
    image: eqalpha/keydb:latest
    command: keydb-server --requirepass ${KEYDB_PASSWORD}
    environment:
      - KEYDB_PASSWORD=${KEYDB_PASSWORD}
    healthcheck:
      test: ["CMD", "keydb-cli", "-a", "${KEYDB_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KEYDB_HOST=keydb
      - KEYDB_PORT=6379
      - KEYDB_PASSWORD=${KEYDB_PASSWORD}
      - JOB_QUEUE=test_queue
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      keydb:
        condition: service_healthy
    command: pytest tests/ -v --log-cli-level=INFO
